mindmap
  root((AMP-IoT / 20MHz IoT))
    Standards
      802.11bp Ambient Power
      Wi-Fi CERTIFIED 7 at 20MHz
    Energy harvesting
      RF
      Light
      Vibration
    TGbp mechanisms
      AMP UL channel access
      AMP receive procedure
      AMP transmit spec
      AMP triggering
      AMP WPT control
    Coexistence
      BLE / Thread / Zigbee market
      HPE Aruba 730 BLE 5.4 + Wi-Fi 7
    Watch
      TGbp draft progress
      Coin-cell / no-battery designs
      AMP-aware Wi-Fi 8 silicon
