mindmap
  root((Satellite direct-to-device))
    Operators
      Starlink direct-to-cell
      AST SpaceMobile BlueBird
      Apple / Globalstar SOS
    Spectrum
      EchoStar 65 MHz mid-band (AWS-3/4, H-Block)
      Earlier FCC D2C spectrum denial
    Strategy shift 2026
      Retail Starlink Mobile ambitions
      Possible terrestrial buildout
    Hardware
      Block 2 BlueBird 2,400 sq ft arrays
      989 Mbps peak D2D measured
    Watch
      EchoStar transfer ~Nov 2027
      Gen2 100x capacity claim
      AST 45-60 satellites by end-2026
      3GPP NTN handset support
