mindmap
  root((Sensing / CSI / RFF))
    802.11bf standard
      Monostatic
      Bistatic
      Multistatic
      Passive
    Protocol modelling
      bf-vs-ax coexistence in ns-3
      Multiband passive sensing
    ML pipelines
      WuKong neuro-wideband
      RF-Lego deep unrolling
      AM-FM CSI foundation model
      Self-supervised sensing
    Meta-learning / domain adaptation
      MU-SHOT-Fi 2605.01369
      EnvCoLoc 2605.10004
    Applications
      Respiratory monitoring
      Activity recognition
      Multi-user counting
      Federated indoor localisation
      RSSI-only sensing
    RFF adjacency
      CSI-RFF microsignals
      FSM device fingerprinting
    Watch
      Productisation gap
      Sensing-privacy regulation
